### ISSUE TITLE
ImportError: cannot import name 'IMAGE' from 'imgx' (/home/hyzhang/ImgX-DiffSeg/imgx/imgx/__init__.py)

### ISSUE THREAD

**Issue by Sere1nz** [mathpluscode/ImgX-DiffSeg#13]
I followed "local with conda" instruction to build environment in linux. 

conda install -y -n base conda-libmamba-solver
conda config --set solver libmamba
conda env update -f docker/environment.yml
conda activate imgx
make pip

I have gone through all these installation steps without error, but when I build amos dataset, it shows the "ImportError: cannot import name 'IMAGE' from 'imgx' (/home/hyzhang/ImgX-DiffSeg/imgx/imgx/__init__.py)"

What should I do in this case?

**Comment by Sere1nz** [comment]
![image](https://github.com/mathpluscode/ImgX-DiffSeg/assets/32921181/61831e7a-775b-48fc-b402-b570232f481f)
![image](https://github.com/mathpluscode/ImgX-DiffSeg/assets/32921181/988dd9b5-91b7-4829-8735-4540342e826c)

**Comment by Sere1nz** [comment]
In new version, IMAGE,LABEL... have moved to imgx_datasets.constant.

**Comment by mathpluscode** [comment]
Hi, it looks like maybe you had two different versions? The code https://github.com/mathpluscode/ImgX-DiffSeg/blob/main/imgx_datasets/imgx_datasets/amos_ct/amos_ct_dataset_builder.py#L11 should be importing from the right path? Please do not hesitate to contact if you have more issues.
