### ISSUE TITLE
How could I run an inference on a single image?

### ISSUE THREAD

**Issue by Sere1nz** [mathpluscode/ImgX-DiffSeg#15]
If I trained a model on a custom dataset, how could I load the model and inference a single image/nii.gz? 
It seems to be a bad idea if i modify the test set in dataset builder and then build it everytime.
Let's say we have an new image that needs to be segmented via the trained 'amos_ct' model. What is the simplest way to inference the image?
Thank  you

**Comment by mathpluscode** [comment]
Hi @Sere1nz thanks for your interest.

Would this test example https://github.com/mathpluscode/ImgX-DiffSeg/blob/main/imgx/tests/unit/test_model_unet.py#L214 be helpful for you?

However, for non-testing scenario, we need to transform the model a bit differently (https://dm-haiku.readthedocs.io/en/latest/api.html). In case you have a runnable example yourself, would you mind sharing it here for other potential users :) thanks!

Overall I see the challenge here and will include an example in the near future. Meanwhile please be aware that we are migrating to Flax #14 (the performance of the models remain similar) and some notebooks/examples will also be provided (if not in the next release, will be in the one after).

**Comment by mathpluscode** [comment]
Hi @Sere1nz, please find an example here: https://github.com/mathpluscode/ImgX-DiffSeg/blob/main/examples/segmentation/inference.ipynb 😃 Hope this can be helpful for you. Note, as we migrated to Flax, this example relies on the latest version of the code, which includes further refactoring to facilitate the inference.
