### ISSUE TITLE
About Encoders

### ISSUE THREAD

**Issue by YonghanLU** [mathpluscode/ImgX-DiffSeg#22]
In your code, you set a bottom encodder and an image encoder. But in your paper, there is only one encoder? Why?

**Comment by mathpluscode** [comment]
Hi @YonghanLU, thanks for your question, the unet consists of
- downsample_encoder/image_encoder
- bottom encoder
- upsample_encoder/mask_decoder

These three parts correspond to the Figure 2 in the paper as illustrated below, hope this clarifies the structure for you :)

<img width="916" alt="image" src="https://github.com/mathpluscode/ImgX-DiffSeg/assets/4066929/08f3f38c-9b95-4288-83d8-97fab9186a0f">

**Comment by YonghanLU** [comment]
I read the codes again an I figure out! Than you very much for your answer.
