### ISSUE TITLE
在amos_ct数据集上训练，好像卡住了

### ISSUE THREAD

**Issue by Destinycjk** [mathpluscode/ImgX-DiffSeg#24]
您好，非常感谢您的精彩的工作。但是在运行过程中，出现了一些问题。我的系统是Ubuntu，按照您的教程配置环境，并在amos_ct数据集上进行训练，其他似乎都没有问题，但是在运行imgx_train data=amos_ct task=gaussian_diff_seg时，运行似乎卡住，在1个小时之后，仍然停留在这里。请问是什么原因呢？由于直接运行会出一些错误，我在按照教程配置完环境后，将scipy降低版本到1.10.1，并将./imgx/conf/config.yaml文件中的project: imgx entity: wandb_entity修改为project:  和entity: 。如上，另外，我观察我的wandb的workspace，结果如下图所示。非常期待您的回答与帮助，谢谢！
![1717226220414](https://github.com/mathpluscode/ImgX-DiffSeg/assets/46669305/3c2e851e-7a3b-4860-ae99-9b2becaf9fe7)
![1717226601778](https://github.com/mathpluscode/ImgX-DiffSeg/assets/46669305/4892b08e-eaeb-4b2f-9bfd-d40cb49628a8)

**Comment by mathpluscode** [comment]
Hi, @Destinycjk 

你遇到的问题可能是因为模型较大 你可以尝试减少模型大小

https://github.com/mathpluscode/ImgX-DiffSeg/blob/277eee4da54c1d1ab46eaee75b1b287f2ddd199a/imgx/conf/task/seg.yaml#L10

也可以直接修改 `debug=True` 这个会自动减小模型大小和训练数据

https://github.com/mathpluscode/ImgX-DiffSeg/blob/277eee4da54c1d1ab46eaee75b1b287f2ddd199a/imgx/conf/config.yaml#L8

Debug config的定义如下

https://github.com/mathpluscode/ImgX-DiffSeg/blob/277eee4da54c1d1ab46eaee75b1b287f2ddd199a/imgx/run_train.py#L25

希望可以帮到你
谢谢
